project:
  type: book
  output-dir: _book
  pre-render: _references.R

lang: fr-FR
bibliography: [book.bib, packages.bib]
# csl: chicago-fullnote-bibliography.csl

crossref:
  eq-prefix: équation
  fig-prefix: figure
  tbl-prefix: tableau
  ref-hyperlink: true

book:
  title: "R pour l'archéologue"
  subtitle: "Exploration, visualisation et analyse de données"
  date: today
  date-format: "YYYY"
  author:
    - name: Nicolas Frerebeau
      orcid: 0000-0001-5759-4944
      affiliations:
        - name: CNRS
    - name: Ben Marwick
      orcid: 0000-0001-7879-4531
      affiliations:
        - name: University of Washington
  output-file: rarcheo

  reader-mode: true
  search: true
  page-navigation: true
  # downloads: [pdf]
  site-url: https://r-archeo.huma-num.fr
  repo-url: https://github.com/nfrerebeau/rarcheo/
  repo-actions: [edit, source, issue]
  
  sidebar: 
   collapse-level: 1
  
  chapters:
  - index.qmd
  - chapters/00-introduction.qmd

  - part: Premiers pas avec R
    chapters:
    - chapters/01-rstats/introduction.qmd
    - chapters/01-rstats/objects.qmd
    - chapters/01-rstats/subsetting.qmd
    - chapters/01-rstats/operators.qmd
    - chapters/01-rstats/flow.qmd
    - chapters/01-rstats/functions.qmd
    
  - part: Vers une recherche reproductible
    chapters:
    - chapters/02-research/reproducibility.qmd
    - chapters/02-research/literate_programming.qmd
    - chapters/02-research/compendium.qmd

  - part: Préparer ses données
    chapters:
    - chapters/03-data/measure.qmd
    - chapters/03-data/variables.qmd
    - chapters/03-data/read_write.qmd
    - chapters/03-data/manipulation.qmd

  - part: Statistiques descriptives
    chapters:
    - chapters/04-statistics/univariate.qmd
    - chapters/04-statistics/bivariate.qmd
    - chapters/04-statistics/outliers.qmd

  - part: Visualisation de données
    chapters:
    - chapters/05-visualization/introduction.qmd
    - chapters/05-visualization/graphs.qmd

  - part: Données de comptage
    chapters:
    - chapters/artefacts/introduction.qmd

  - part: Données de composition
    chapters:
    - chapters/coda/introduction.qmd
    - chapters/coda/transformations.qmd
    - chapters/coda/outliers.qmd

  - part: Chronologie
    chapters:
    - chapters/chronology/introduction.qmd
    - chapters/chronology/relative.qmd
    - chapters/chronology/absolute.qmd

  - part: Analyse spatiale
    chapters:
    - chapters/spatial/introduction.qmd

  - part: Analyse de réseaux
    chapters:
    - chapters/network/introduction.qmd
    
  - chapters/00-references.qmd
    
  appendices:
    - chapters/appendix/setup.qmd
    - chapters/appendix/cheat_sheet.qmd
    - chapters/appendix/good_practices.qmd
    - chapters/appendix/style.qmd
    - chapters/appendix/ggplot2.qmd
    
format:
  html:
    lang: fr
    theme: cosmo
    code-link: true
    toc: true
    number-sections: true
    link-external-icon: true
    license: CC BY-NC-SA
    description: |
      Ce livre s'adresse aux personnes qui souhaitent analyser, visualiser et 
      modéliser des données archéologiques à l'aide du langage R. Cet ouvrage 
      doit vous permettre d'acquérir les connaissances et les compétences 
      nécessaires pour aborder un large éventail de problèmes liés aux données 
      archéologiques.
    mainfont: Atkinson Hyperlegible
    include-in-header:
      - head.html
    
  pdf:
    lang: fr
    documentclass: scrbook
    classoption: 
      - french
      - 12pt
      - a4paper
      - twoside
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    pdf-engine: lualatex
    toc: true
    lof: true
    lot: true
    toc-depth: 2
    toc-title: Sommaire

editor: source

execute:
  freeze: auto
  
# Set default options for every webpage that may or may not include webR.
engine: knitr
webr: 
  show-startup-message: true     # Display status of webR initialization
#  show-header-message: false     # Check to see if COOP&COEP headers are set for speed.
#  packages: ['ggplot2', 'dplyr'] # Pre-install dependencies
#  base-url: ''                   # Base URL used for specifying where R WebAssembly binaries should be located
#  home-dir: '/home/rstudio'      # Customize where the working directory is
#  channel-type: 'post-message'   # Specify communication channel
#  service-worker-url: ''         # URL from where to load JavaScript worker scripts when loading webR with the ServiceWorker communication channel.

# Attach webR to every page
filters:
  - webr

knitr:
  opts_chunk:
    echo: true
    collapse: true
    comment: "#>"
    dpi: 300
    out-width: "100%"
    fig-align: "center"
    fig-width: 7
    fig-height: 5
    width: 68
