\mainmatter

# (PART) Introduction {-}

# Pourquoi travailler avec R

## Conventions d'écriture

Par la suite, on écrira `foo()` pour désigner une fonction, `bar` pour désigner les variables et les paramètres des fonctions et `baz/` pour désigner les chemins. Les noms de *packages* sont indiqués en italique.

Les commentaires dans le code sont précédés par le signe `#`. Les blocs de code alternent l'entrée et la sortie. La sortie est commentée (précédée par `#>` pour la distinguer des commentaires standards) de sorte que vous pouvez facilement copier et coller les exemples dans R.

## Note sur le *tidyverse*

Le [tidyverse](https://www.tidyverse.org/) est un ensemble de packages partageant "une philosophie de conception, une grammaire et des structures de données" dont les principes sont détaillés par @wickham2019b. Tout comme le tidyverse est "dogmatique" (*opinionated*), ce livre revendique un choix : celui de ne pas utiliser les packages du tidyverse, malgré leur popularité au sein de la communauté des utilisateurs de R.

Ce choix repose sur un constat simple : l'usage de ces packages tend à considérablement complexifier l'apprentissage de R par les débutants et à les enfermer dans un écosystème particulier. Au contraire, l'utilisateur qui maîtrise les bases de R peut faire face à une multitudes de situations à l'aide de quelques opérations simples.

Ceci étant dit, le lecteur qui le souhaite trouvera dans [*R for Data Science*](https://r4ds.had.co.nz/) [@wickham2016] une introduction à l'analyse de données avec les packages du tidyverse.

# Ressources complémentaires

Il existe de très nombreux ouvrages consacrés à R, dont la plupart sont consultables en ligne.
*R in a Nutshell* de @adler2010 et [*R cookbook*](https://rc2e.com/) de @long2019 couvrent les usages élémentaires du langage (plus qu'ils ne sont traités ici) et sont d'une aide précieuse pour un usage courrant.

L'ouvrage de référence de @murrell2019, *R graphics*, offre une vue d'ensemble des fonctionnalités graphiques de R et de leur usage avancé. [*R Graphics Cookbook*](https://r-graphics.org/) [@chang2012] constitue également une référence indispensable et fournit des recettes clé en main pour la création de graphiques. Quiconque s'attachant à réaliser des graphiques informatifs et convaincants consultera avec intérêt [*Fundamentals of Data Visualization*](https://clauswilke.com/dataviz/) de @wilke2019.

L'utilisateur confirmé trouvera dans les ouvrages [*Advanced R*](https://adv-r.hadley.nz/) [@wickham2019], [*Efficient R programming*](https://csgillespie.github.io/efficientR/) [@gillespie2016] et [*R packages*](https://r-pkgs.org/) [@wickham2015] de quoi approfondir sa compréhension du langage et développer sa pratique (notamment pour le développement de packages).

Enfin, on trouvera sur le [site du package bookdown](https://bookdown.org/home/) de nombreux ouvrages supplémentaires, librement consultables en ligne. Le site du projet R propose également [une liste d'ouvrages dédiés à R et ses applications](https://www.r-project.org/doc/bib/R-books.html).
