# Reproductibilité et réplicabilité {#sec-reproducibility}

La **reproductibilité** désigne la capacité d'un chercheur à reproduire les résultats d'une étude antérieure en utilisant les mêmes matériaux que ceux utilisés par le chercheur initial [@goodman2016]. Il s'agit d'une pierre angulaire de la recherche scientifique, car si nous ne pouvons pas reproduire des études antérieures, nous ne pouvons pas nous fier à leurs résultats, et nous ne pouvons pas nous appuyer dessus pour produire de nouvelles connaissances. 

## Quel rapport entre R et reproductibilité ?

Lorsque nous interagissons avec R en écrivant des commandes dans un fichier texte, nous pouvons sauvegarder ce script, le partager et l'archiver : nous réalisons notre analyse d'une manière qui peut être reproduite par d'autres. À l'opposé, l'analyse de données dans un tableur ou dans un autre logiciel à interface graphique, piloté par la souris, ne laissent aucune trace car de nombreuses étapes intermédiaires sont typiquement des clics de souris. Une autre personne inspectant votre fichier issu d'un tableur peut avoir du mal à identifier les décisions que vous avez prises dans votre analyse en raison des nombreuses étapes éphémères et non enregistrées qui ont conduit au résultat final.

## Pourquoi s'attacher à la reproductibilité de la recherche ? 

Quatre facteurs ont conduit à des préoccupations croissantes quant à la reproductibilité des résultats scientifiques dans la science moderne :

* Le premier facteur est la reprise d'expériences biomédicales marquantes qui n'ont pas donné les mêmes résultats que la publication initiale [@prinz2011]. 
* Le deuxième facteur est la découverte d'études très médiatisées dont les résultats publiés étaient erronés en raison d'erreurs d'analyse des données [@baggerly2009; @herndon2014]. 
* Troisièmement, il y a eu une forte augmentation du nombre de publications savantes qui ont été rétractées en raison de la découverte d'inconduites telles que des données frauduleuses et du plagiat [@vannoorden2011; @steen2013]. 
* Enfin, on a assisté à une augmentation des recherches qui utilisent massivement des simulations informatiques ou collectent des quantités énormes de données à partir d'un grand nombre de capteurs (par exemple, l'astronomie et l'océanographie). 

Ces événements ont suscité un vaste débat dans de nombreuses disciplines sur la manière d'améliorer la reproductibilité de la recherche scientifique. Certaines de ces discussions ont abouti à des appels de diverses disciplines [@nosek2015] pour que les publications soient accompagnées à la fois des données brutes [@reichman2011] et du code utilisé lors de l'analyse des données [@barnes2010; @ince2012; @morin2012]. En lien avec ces appels, on trouve des articles publiés sous la forme de manifestes rédigés par des groupes de chercheurs qui demandent des changements substantiels dans la recherche afin d'améliorer la reproductibilité et la transparence [@wilson2014; @hampton2015; @sandve2013]. Dans le cadre de l'archéologie, ces principes sont explorés en détail par @marwick2017.

Avant toute chose, nous devons préciser ce que nous entendons ici par "reproductible", car le terme n'est pas très répandu en archéologie. Il existe des ambiguïtés autour de l'utilisation de ce terme, notamment au regard de concepts étroitement liés tels que **réplicabilité** et **fiabilité** [@baker2016; @plesser2018]. [*The Turing Way*](https://the-turing-way.netlify.app/) définit une recherche reproductible comme "un travail qui peut être recréé de manière indépendante à partir des mêmes données et du même code que ceux utilisés par l'équipe originale" et opère une distinction entre les notions de reproductibilité, de replicabilité, de robustesse et de généralisation (@tbl-reproductibilite). Nous retiendrons ici la définition et la taxinomie de la reproductibilité proposées par @stodden2014, qui divise le concept en trois parties : empirique, computationnelle et statistique.

```{r}
#| label: tbl-reproductibilite
#| echo: false
#| tbl-cap: Définition d'une recherche reproductible d'après *The Turing Way*.
repro <- data.frame(
  data = c("Analyse identique", "Analyse différente"),
  identique = c("Reproductible", "Robuste"),
  different = c("Réplicable", "Généralisable")
)


knitr::kable(repro, booktabs = TRUE, 
             col.names = c("", "Données identiques", "Données différentes"))
```

## Les trois aspects de la reproductibilité

Le premier aspect est la **reproductibilité empirique** ou réplicabilité. Pour un archéologue, cela signifie évaluer un résultat obtenu précédemment en procédant à une nouvelle fouille d'un site qu'un autre chercheur a déjà fouillé, en étudiant une collection de musée qui a déjà été étudiée par une autre personne ou en répétant une expérience qui avait déjà été publiée. La reproductibilité empirique consiste à retourner à la source des données et à les collecter à nouveau. Les archéologues le font régulièrement, par exemple, en retournant sur des sites célèbres tels que Le Moustier (Dordogne, France) ou Çatal Höyük (Anatolie, Turquie) pour les fouiller à nouveau. Cela se produit généralement des décennies après les fouilles originales qui ont rendu le site célèbre. Il ne s'agit pas d'une reproductibilité empirique exacte, car nous n'utilisons pas exactement les mêmes procédures que les équipes précédentes, mais des méthodes de terrain modernes pour collecter davantage de données et améliorer et étendre les travaux antérieurs. L'idée générale de tester les affirmations précédentes est généralement la principale motivation pour retourner sur un site.

Les deuxième et troisième parties de la reproductibilité sont la reproductibilité computationnelle et statistique. La **reproductibilité computationnelle** consiste à refaire les calculs d'un autre chercheur en utilisant ses données et ses méthodes (c'est-à-dire son code). Ce type de reproductibilité n'implique pas la collecte de données nouvelles, mais utilise les méthodes et les données recueillies par le chercheur original. L'amélioration de la reproductibilité computationnelle nécessite la préservation de l'ensemble des étapes de préparation des données brutes en vue de leur analyse. La **reproductibilité statistique** est quant à elle accrue lorsque des informations détaillées sont communiquées sur le choix des tests statistiques, les paramètres des modèles, les valeurs seuils et autres détails qui déterminent les résultats des analyses statistiques.

Les notions de reproductibilité computationnelle et reproductibilité statistique sont peu familières pour la plupart des archéologues, car notre culture disciplinaire tend à valoriser le secret et la confidentialité, plutôt que le partage et l'ouverture des détails (souvent banals) de nos analyses. De nombreux archéologues considèrent la rédaction d'une publication comme l'écriture d'un roman. Le processus créatif et la rédaction du roman sont généralement un processus personnel et privé que l'auteur garde pour lui. De même, les lecteurs du roman ne s'attendent généralement pas à voir les ébauches ou à être informé du processus de création. L'auteur et le lecteur ont une compréhension commune du fait que le roman publié est le produit final, et qu'aucun autre matériel (par exemple, des brouillons antérieurs, des notes, des ébauches) n'est nécessaire pour lui donner un sens. Cela s'explique par le fait que le roman est avant tout un produit artistique, sa valeur provenant de la façon dont il suscite les émotions du lecteur. Les premières versions d'un roman n'ont généralement aucune incidence sur la valeur du roman final tel qu'il est publié. Bien sûr, il y a des exceptions : nous aimons souvent entendre l'auteur d'un roman parler de ses inspirations et de ses motifs dans des interviews, et les spécialistes de la littérature trouvent de la valeur dans les notes et les accessoires des écrivains. Cependant, la plupart du temps, ces détails ne font pas partie du contrat tacite entre l'auteur de fiction et ses lecteurs.

La recherche archéologique, comme les autres sciences, est fondamentalement différente de l'écriture de romans. Néanmoins, les normes traditionnelles de l'érudition, qui consistent à ne rien partager à l'exception de l'article final publié, tendent à renforcer le modèle du romancier. La valeur d'une publication archéologique n'est pas esthétique, mais réside dans la valeur de vérité des affirmations faites sur le comportement humain dans le passé. Pour permettre une évaluation solide de ces affirmations, le lecteur peut avoir besoin de connaître les détails du processus analytique qui ne sont pas présentés dans la publication finale. Il y a de nombreuses raisons pour lesquelles des détails pertinents peuvent ne pas être inclus dans une publication. Nous ne pouvons pas anticiper et répondre à toutes les questions potentielles dans l'espace limité d'un article scientifique. En conséquence, nous (en tant qu'auteurs) n'avons pas le dernier mot quant aux données et détails méthodologiques qui sont nécessaires pour faire valoir nos arguments : les éléments nécessaires sont ceux que nos lecteurs (nos pairs) exigent.

Cette relation auteur-lecteur scientifique est très différente de la relation auteur-lecteur de roman. Dans notre cas, en mettant publiquement à disposition nos données et notre code au moment de la publication, nous permettons à nos lecteurs de trouver le matériel dont ils ont besoin pour évaluer nos arguments et réutiliser notre travail. De nombreuses disciplines modifient leurs pratiques scientifiques en reconnaissant cette relation particulière entre l'auteur et le lecteur. Un compte rendu complet dépasse le cadre de ce chapitre, mais ces nouvelles façons de faire de la science sont disponibles pour l'océanographie [@lowndes2017] et la géologie [@bond-lamberty2016], par exemple.

Pour en revenir à la question de la reproductibilité computationnelle, l'un des problèmes les plus urgents est que nos publications incluent rarement suffisamment de données pour permettre une réanalyse, et que nos méthodes sont rarement présentées de manière suffisamment détaillée pour permettre à une autre personne de la répéter de manière indépendante. Cette situation devient un problème de plus en plus important pour la recherche archéologique récente en raison des évolutions et de la diffusion rapide des méthodes numériques. Sauf à changer nos pratiques, il peut devenir difficile de faire confiance aux résultats publiées, et difficile de réutiliser les recherches nouvellement publiées. Pour améliorer à la fois la reproductibilité computationnelle et la reproductibilité statistique, les archéologues doivent inclure les données et le code utilisés dans leurs publications.

Dans les chapitres qui suivent, nous montrons comment les archéologues peuvent répondre à ces appels à une reproductibilité et une transparence accrues. Nous y décrivons deux principes clés : la programmation lettrée (ou programmation littérale) [@knuth1984] (@sec-reproducibility-literate) et l'élaboration d'un **compendium** (@sec-collect). Enfin, si les enjeux de transparence de la recherche vous intéressent, il vous faudra sans doute compléter votre maîtrise de R par des outils supplémentaires, notamment le contrôle de version [@bryan2021].

:::{.callout-tip}
## The Turing Way

Le collectif [The Turing Way](https://the-turing-way.netlify.app) a pour objectif de fournir aux chercheurs toutes les informations nécessaires pour travailler de manière reproductible.

> The Turing Way community is dedicated to making collaborative, reusable and transparent research "too easy not to do". That means investing in the socio-technical skills required to work in a team, to build something more significant than any individual could deliver alone. --- [The Turing Way](https://the-turing-way.netlify.app)

*The Turing Way* est également un livre, organisé sous forme de guides pouvant être consultés indépendamment les uns des autres en fonction des besoins.
:::
