# Introduction {#collect-introduction}

L'objectif de ce chapitre est d'expliquer comment des décisions prises avant et pendant la collecte des données peuvent permettre d'économiser du temps et des efforts plus tard, pendant le processus d'analyse et de visualisation des données, en utilisant R ou tout autre outil. Le chapitre est organisé de manière hiérarchique, en commençant par l'organisation des fichiers au niveau du projet, puis en descendant pour discuter de l'organisation efficace des feuilles de calcul (l'un des outils les plus courants pour collecter, partager et stocker les données archéologiques), et enfin au niveau très granulaire de la cellule individuelle dans une feuille de calcul.

Le gain de temps et d'efforts est bien sûr une motivation importante pour modifier vos pratiques en matière de collecte et d'organisation des données, mais il existe un objectif plus large. Cet objectif est double :

* D'une part, cela permet participe à améliorer la reproductibilité de la recherche. Lorsqu'un projet est bien organisé, il est plus facile de trouver les fichiers clés pour vérifier les résultats obtenus. 
* D'autre part, cela doit conduire à la production de jeux de données interopérables à grande échelle. De sorte que les données de divers projets puissent être facilement combinées pour répondre à des questions qu'aucun projet ne peut résoudre seul.

Cette double approche de l'organisation des données repose sur d'autres aspects, telles que la volonté de partager les données et de les rendre accessibles au public, ainsi qu'un consensus sur ce qu'il faut mesurer et comment nommer les variables. Si le partage de vos données est la première étape pour permettre leur réutilisation --- ce qui n'est pas encore courant en archéologie --- elles doivent également être faciles à comprendre pour que d'autres puissent facilement les réutiliser [@white2013].

Une grande partie de ce chapitre ne présente pas de complexité particulière et peut sembler relever du bon sens. Cependant, les pratiques décrites ici font une grande différence quant à la réutilisation des données. Il nous semble donc important de les discuter directement et explicitement, plutôt que de supposer que tout un chacun les assimilera en cours de route sans conseils ou instructions spécifiques. Ce chapitre s'appuie sur des documents du domaine public, préparés à l'origine par Jenny Bryan, Karl Broman et d'autres pour le programme science reproductible de Data Carpentry, ainsi que sur des sources provenant d'autres disciplines, comme @borer2009, @sutter2015, @volk2014, @hampton2013, @strasser2012.
